movie_project/movie_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movie_project import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/movieapp/urls.py
from django.contrib import admin
from django.urls import path, include

from movieapp import views
app_name = 'movieapp'
urlpatterns = [
    path("", views.index, name='index'),
    path('movie_list/<int:movie_id>', views.details, name='details'),
    path("add/", views.add_movie, name='add_movie'),
    path('update/<int:movie_id>', views.update, name='update'),
    path('delete/<int:movie_id>', views.delete, name='delete')
]

movie_project/movieapp/models.py
from django.db import models

# Create your models here.

class movie_list(models.Model):
    name = models.CharField(max_length=100)
    year = models.IntegerField(blank=True)
    director = models.CharField(max_length=100)
    img = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

movie_project/movieapp/views.py
from django.shortcuts import render, redirect

from .form import Movieform
from .models import movie_list


# Create your views here.

def index(request):
    movies = movie_list.objects.all()
    return render(request, 'index.html', {'movies': movies})


def details(request, movie_id):
    movie = movie_list.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    length = len(movie_list.objects.all())
    if request.method == 'POST':
        name = request.POST.get('name', )
        year = request.POST.get('year', )
        director = request.POST.get('director', )
        img = request.FILES.get('img', )
        movie = movie_list(id=length + 1, name=name, year=year, director=director, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')


def update(request, movie_id):
    movie = movie_list.objects.get(id=movie_id)
    form = Movieform(request.POST or None, request.FILES or None, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form': form, 'movie': movie})


def delete(request, movie_id):
    if request.method == 'POST':
        movie = movie_list.objects.get(id=movie_id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html', {'movie': movie_list.objects.get(id=movie_id)})

movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<h2 style="margin-top: 20px; text-align: center;">Add new Movie</h2>
<div class="add">
<form id='add_movie' action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label class="label" for="">Movie Name : </label>
    <input type="text" name="name" placeholder="Favorite movie" ><br>
    <label class="label" for="">Released Year : </label>
    <input type="text" name="year" placeholder="Year of Movie"><br>
    <label class="label" for="">Director Name : </label>
    <input type="text" name="director" placeholder="Director of movie"><br>
    <label class="label" for="">Image : </label>
    <input  type="file" name="img" placeholder="Favorite movie"><br>
    
</form>
<button form="add_movie" class="input" type="submit">Add Movie</button>
<a href="{% url 'movieapp:index' %}"><button>Cancel</button></a>
</div>

{% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Theater</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'movieapp:index' %}">
            <img src={% static "images/movies.jpg" %} alt="" width="30" height="24" class="d-inline-block align-text-top">
            Movie Theater
          </a>
          <div style="margin: 20px; text-align: right;">
            <a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}" >Add Movie</a>
          </div>

        </div>
        
      </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

movie_project/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div style="text-align: center; padding-top: 30px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Do you want to delete {{ movie.name}}?</h3>
        <input type="submit" class="btn btn-warning" value="Yes">
        <a class="btn btn-info" href="{% url 'movieapp:details' movie.id %}" >No</a>
    </form>
</div>

{% endblock %}

movie_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="movie">
    <img src="{{ movie.img.url }}" alt="" width="200" height="250"><br>
    <h2>{{ movie.name }}</h2><br>
    <h3>{{ movie.year }}</h3><br>
    <h3>{{ movie.director }}</h3><br>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update Movie</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete Movie</a>

</div>


{% endblock %}

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
            {% for movie in movies %}
            <div class="col-lg-4 col-md-6 col-sm-12 ">
                <div class="card" style="width: 18rem; margin-top: 25px;">
                    <img class="card-img-top" src="{{ movie.img.url }}" alt="Card image cap" width="150" height="300">
                    <div class="card-body text-center">
                      <h5 class="card-title">{{movie.name}}</h5>
                      <p class="card-text">{{movie.director}}</p>
                      <p class="card-text">{{movie.year}}</p>
                      <a href="{% url 'movieapp:details' movie.id %}" class="btn btn-primary ">View Details</a>
                    </div>
                  </div>
            </div>
            {% endfor %}
    </div>
</div>




{% endblock %}

movie_project/templates/update.html
{% extends 'base.html' %}
{% block body %}
<h2 style="margin-top: 20px; text-align: center;">Update Movie</h2>
<div class="add" style="margin-top: 20px;">
    <form id="update" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
    </form>
    <button form="update" class="input" type="submit">Update Movie</button>
    <a class="input" href="{% url 'movieapp:details' movie.id %}" ><button>Cancel</button></a>
</div>

{% endblock %}